name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-12, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        exclude:
          - platform: macos-12
            python-version: "3.7"
          - platform: macos-12
            python-version: "3.8"
          - platform: macos-12
            python-version: "3.9"
    runs-on: ${{ matrix.platform }}
    env:
      SYSTEM_VERSION_COMPAT: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip uninstall aubio
          pip install pydub
          pip install https://files.pythonhosted.org/packages/02/41/c0a7c26e5f9b0de15cc84836da15448bab3355aa11ca973eb39c75799aa3/essentia-2.1b6.dev858-cp310-cp310-manylinux_2_17_i686.manylinux2014_i686.whl
          pip install -r requirements.txt
          pip install --no-cache-dir https://github.com/aubio/aubio/archive/refs/tags/0.4.9.tar.gz

      - name: Run tests
        run: pytest -v tests/test_audio_slicer.py
