name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-20.04, ubuntu-latest, windows-2019, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
        test-command: ["pytest -v tests/test_audio_slicer.py"]
    runs-on: ${{ matrix.platform }}
    env:
      SYSTEM_VERSION_COMPAT: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        timeout-minutes: 10
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest

      - name: Install FFmpeg on Ubuntu
        if: startsWith(matrix.platform, 'ubuntu')
        timeout-minutes: 5
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install FFmpeg on Windows
        if: startsWith(matrix.platform, 'windows')
        timeout-minutes: 5
        run: |
          choco install ffmpeg -y

      - name: Install FFmpeg on macOS
        if: startsWith(matrix.platform, 'macos')
        timeout-minutes: 5
        run: |
          brew install ffmpeg

      - name: Run tests
        timeout-minutes: 5
        run: ${{ matrix.test-command }}
