name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-20.04, ubuntu-latest, windows-2019, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.platform }}
    env:
      SYSTEM_VERSION_COMPAT: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        timeout-minutes: 10
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest

      - name: Install FFmpeg
        timeout-minutes: 10
        run: |
          if [ "${{ matrix.platform }}" == "ubuntu-20.04" ] || [ "${{ matrix.platform }}" == "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y ffmpeg
          else
            pip install ffmpeg
          fi

      - name: Run tests
        timeout-minutes: 5
        run: pytest -v tests/test_audio_slicer.py
